blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('post/', views.PostList.as_view(), name='post_list'),
    path('category/<int:pk>/', views.BlogCategoryList.as_view(), name='blog_category_list'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.ProjectList.as_view(), name='project_list'),
    path('detail/<int:pk>/', views.ProjectDetail.as_view(), name='project_detail'),
]

blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=120)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=120)
    body = models.TextField()
    categories = models.ManyToManyField(Category, related_name='posts')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=120)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=50)
    image = models.ImageField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    author = forms.CharField(max_length=100, widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Your name"}))
    body = forms.CharField(widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Leave a comment..."}))
    

blog/views.py
from email import message
from re import template
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView
from .models import Post, Category, Comment
from .forms import CommentForm
from django.contrib import messages

class PostList(ListView):
    template_name = 'blog/blog_list.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        return self.model.objects.all().order_by('-created')


class BlogCategoryList(ListView):
    template_name = 'blog/blog_category.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs.get('pk')
        context['category'] = get_object_or_404(self.model, pk=pk)
        return context


class PostDetail(View):
    template_name = 'blog/blog_detail.html'
    form_class = CommentForm

    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        comments = Comment.objects.filter(post=post)
        form = self.form_class
        return render(request, self.template_name, {"post": post, "form": form, "comments": comments})

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = self.form_class(request.POST or None)
        if form.is_valid():
            comment = Comment(
            author=form.cleaned_data["author"], body=form.cleaned_data["body"], post=post)
            comment.save()
            comments = Comment.objects.filter(post=post)
            messages.success(request, 'You add a comment.', 'success')
            form = self.form_class
        else:
            messages.error(request, 'an error occurred', 'warning')

        return render(request, self.template_name, {"post": post, "form": form, "comments": comments})

portfolio/views.py
from django.views.generic import ListView, DetailView
from .models import Project


class ProjectList(ListView):
    template_name = 'portfolio/project_list.html'
    model = Project
    context_object_name = 'projects'


class ProjectDetail(DetailView):
    template_name = 'portfolio/project_detail.html'
    model = Project
    context_object_name = 'project'

blog/templates/blog/blog_category.html
{% extends 'base.html' %}

{% block title %} Category {% endblock title %}

{% block content %}
<div class="col-md-8 offset-md-2">

    <h1>{{ category | title }}</h1>

    <hr>

    {% for post in category.posts.all %}

        <h2><a href="{% url 'blog:post_detail' post.pk%}">{{ post.title }}</a></h2>

        <small>

            {{ post.created.date }} |&nbsp;

            Categories:&nbsp;

            {% for category in post.categories.all %}

            <a href="{% url 'blog:blog_category_list' category.pk %}">

                {{ category.name }}

            </a>&nbsp;

            {% endfor %}

        </small>

        <p>{{ post.body | slice:":400" }}...</p>

    {% endfor %}

</div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %} Blog | {{ post.title }} {% endblock title %}

{% block content %}
<div class="col-md-8 offset-md-2">

    <h1>{{ post.title }}</h1>

    <small>

        {{ post.created }} |&nbsp;

        Categories:&nbsp;

        {% for category in post.categories.all %}

        <a href="{% url 'blog:blog_category_list' category.pk %}">

            {{ category.name }}

        </a>&nbsp;

        {% endfor %}

    </small>

    <p>{{ post.body | linebreaks }}</p>

    <h3>Leave a comment:</h3>

    <form action="" method="post">

        {% csrf_token %}

        <div class="form-group">

            {{ form.author }}

        </div>

        <div class="form-group">

            {{ form.body }}

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

    <hr>

    {% if comments %}
        {% for comment in comments %}
            <h3>Comments:</h3>
            <p>

                On {{comment.created }}&nbsp;

                <b>{{ comment.author }}</b> wrote:

            </p>

            <p>{{ comment.body }}</p>

            <hr>

        {% endfor %}
    {% else %}
            <h3>No comments</h3>
    {% endif %}

</div>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %} Posts {% endblock title %}

{% block content %}
<div class="col-md-8 offset-md-2">

    <h1>{{ category | title }}</h1>

    <hr>

    {% for post in posts %}

        <h2><a href="{% url 'blog:post_detail' post.pk%}">{{ post.title }}</a></h2>

        <small>

            {{ post.created.date }} |&nbsp;

            Categories:&nbsp;

            {% for category in post.categories.all %}

            <a href="{% url 'blog:blog_category_list' category.pk %}">

                {{ category.name }}

            </a>&nbsp;

            {% endfor %}

        </small>

        <p>{{ post.body | slice:":400" }}...</p>

    {% endfor %}

</div>
{% endblock content %}

portfolio/templates/portfolio/project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Project Detail{% endblock title %}

{% block content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{{ project.image.url }}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
    </div>
</div>
{% endblock content %}

portfolio/templates/portfolio/project_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Portfolio | Project List{% endblock title %}

{% block content %}
<h1>Projects</h1>

<div class="row">

{% for project in projects %}

    <div class="col-md-4">

        <div class="card mb-2">

            <img class="card-img-top" src="{{ project.image.url }}">

            <div class="card-body">

                <h5 class="card-title">{{ project.title }}</h5>

                <p class="card-text">{{ project.description | truncatewords:30 }}</p>

                <a href="{% url 'portfolio:project_detail' project.pk %}"

                   class="btn btn-primary">

                    Read More

                </a>

            </div>

        </div>

    </div>

    {% endfor %}

</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
        {% include 'messages.html' %}
        {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/messages.html
{% load static %}
{% if messages %}
{% for message in messages %}
    <br>
    <p class="alert alert-{{ message.tags }}" style="margin-top: 10px;">{{ message }}</p>
{% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'portfolio:project_list' %}">Portfolio</a>
      <a class="nav-link active" href="{% url 'blog:post_list' %}">Blog</a>
    </div>
  </div>
</nav>